# Generated by Django 3.2 on 2025-12-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeedApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('sent', 'sent'), ('accepted', 'accepted')], default='sent', max_length=8),
        ),
    ]
